apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-diplom-app-deployment
  labels:
    app: my-diplom-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-diplom-app
  template:
    metadata:
      labels:
        app: my-diplom-app
    spec:
      containers:
      - name: my-diplom-app
        image: perovss/nginx.app:latest
        ports:
        - containerPort: 80
          name: http