apiVersion: v1
kind: Service
metadata:
  labels:
    app: diplom-app
  name: diplom-app
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 3001
    targetPort: http
  selector:
    app: diplom-app
