apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-diplom-app
  name: my-diplom-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30001
  selector:
    app: my-diplom-app
